-- MySQL Script generated by MySQL Workbench
-- Wed Nov 20 09:06:12 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tc` DEFAULT CHARACTER SET utf8 ;
USE `tc` ;

-- -----------------------------------------------------
-- Table `tc`.`tipo_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tc`.`tipo_usuario` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tc`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tc`.`usuario` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(200) NOT NULL,
  `fone` VARCHAR(16) NULL DEFAULT NULL,
  `endereco` VARCHAR(200) NULL DEFAULT NULL,
  `bairro` VARCHAR(100) NULL DEFAULT NULL,
  `cidade` VARCHAR(100) NULL DEFAULT NULL,
  `cargo` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(32) NOT NULL,
  `ultimaSenha` VARCHAR(32) NULL DEFAULT NULL,
  `token` VARCHAR(32) NULL DEFAULT NULL,
  `status` INT(2) NOT NULL,
  `cadastro` DATETIME NOT NULL,
  `tipo_usuario_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `tipo_usuario_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_usuario_tipo_usuario1_idx` (`tipo_usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_tipo_usuario1`
    FOREIGN KEY (`tipo_usuario_id`)
    REFERENCES `tc`.`tipo_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tc`.`auditoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tc`.`auditoria` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo` INT(1) NOT NULL,
  `usuario_id` INT(11) NOT NULL,
  `tabela` VARCHAR(60) NOT NULL,
  `campos` TEXT NULL DEFAULT NULL,
  `descricao` TEXT NULL DEFAULT NULL,
  `data` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_auditoria_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_auditoria_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `tc`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 215
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tc`.`permissao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tc`.`permissao` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(50) NOT NULL,
  `nivel` INT(2) NOT NULL,
  `status` INT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tc`.`veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tc`.`veiculo` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo` INT(2) NULL DEFAULT NULL,
  `modelo` VARCHAR(100) NULL DEFAULT NULL,
  `placa` VARCHAR(8) NOT NULL,
  `cidadePlaca` VARCHAR(100) NULL DEFAULT NULL,
  `cor` VARCHAR(60) NULL DEFAULT NULL,
  `observacoes` TEXT NULL DEFAULT NULL,
  `cadastro` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 95
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tc`.`registro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tc`.`registro` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `usuario_id` INT(11) NOT NULL,
  `veiculo_id` INT(11) NOT NULL,
  `entrada` DATETIME NOT NULL,
  `saida` DATETIME NULL DEFAULT NULL,
  `condutor` VARCHAR(100) NULL DEFAULT NULL,
  `motivo` INT(2) NULL DEFAULT NULL,
  `descricao` TEXT NULL DEFAULT NULL,
  `status` INT(1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuario_has_veiculo_veiculo1_idx` (`veiculo_id` ASC) VISIBLE,
  INDEX `fk_registro_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_registro_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `tc`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_veiculo_veiculo1`
    FOREIGN KEY (`veiculo_id`)
    REFERENCES `tc`.`veiculo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 228
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tc`.`tipo_usuario_permissao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tc`.`tipo_usuario_permissao` (
  `tipo_usuario_id` INT(11) NOT NULL,
  `permissao_id` INT(11) NOT NULL,
  PRIMARY KEY (`tipo_usuario_id`, `permissao_id`),
  INDEX `fk_tipo_usuario_has_permissao_permissao1_idx` (`permissao_id` ASC) VISIBLE,
  INDEX `fk_tipo_usuario_has_permissao_tipo_usuario1_idx` (`tipo_usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_tipo_usuario_has_permissao_permissao1`
    FOREIGN KEY (`permissao_id`)
    REFERENCES `tc`.`permissao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tipo_usuario_has_permissao_tipo_usuario1`
    FOREIGN KEY (`tipo_usuario_id`)
    REFERENCES `tc`.`tipo_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
