-- MySQL Script generated by MySQL Workbench
-- Wed Aug 28 00:45:33 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tipo_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(100) NOT NULL,
  `status` INT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `foto` VARCHAR(45) NULL,
  `email` VARCHAR(200) NOT NULL,
  `fone` VARCHAR(16) NULL,
  `endereco` VARCHAR(200) NULL,
  `bairro` VARCHAR(100) NULL,
  `cidade` VARCHAR(100) NULL,
  `cargo` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(32) NOT NULL,
  `ultimaSenha` VARCHAR(32) NULL,
  `token` VARCHAR(32) NULL,
  `status` INT(2) NOT NULL,
  `cadastro` DATETIME NOT NULL,
  `tipo_usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`, `tipo_usuario_id`),
  INDEX `fk_usuario_tipo_usuario_idx` (`tipo_usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_tipo_usuario`
    FOREIGN KEY (`tipo_usuario_id`)
    REFERENCES `mydb`.`tipo_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`permissao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`permissao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(50) NOT NULL,
  `nivel` INT(2) NOT NULL,
  `status` INT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_usuario_permissao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_usuario_permissao` (
  `tipo_usuario_id` INT NOT NULL,
  `permissao_id` INT NOT NULL,
  PRIMARY KEY (`tipo_usuario_id`, `permissao_id`),
  INDEX `fk_tipo_usuario_has_permissao_permissao1_idx` (`permissao_id` ASC) VISIBLE,
  INDEX `fk_tipo_usuario_has_permissao_tipo_usuario1_idx` (`tipo_usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_tipo_usuario_has_permissao_tipo_usuario1`
    FOREIGN KEY (`tipo_usuario_id`)
    REFERENCES `mydb`.`tipo_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tipo_usuario_has_permissao_permissao1`
    FOREIGN KEY (`permissao_id`)
    REFERENCES `mydb`.`permissao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`veiculo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` INT(2) NULL,
  `modelo` VARCHAR(100) NULL,
  `placa` VARCHAR(8) NOT NULL,
  `cidadePlaca` VARCHAR(100) NULL,
  `cor` VARCHAR(60) NULL,
  `observacoes` TEXT NULL,
  `cadastro` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`registro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`registro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo_usuario_id` INT NOT NULL,
  `veiculo_id` INT NOT NULL,
  `entrada` DATETIME NOT NULL,
  `saida` DATETIME NULL,
  `condutor` VARCHAR(100) NULL,
  `motivo` INT(2) NULL,
  `descricao` TEXT NULL,
  `status` INT(1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuario_has_veiculo_veiculo1_idx` (`veiculo_id` ASC) VISIBLE,
  INDEX `fk_usuario_has_veiculo_usuario1_idx` (`id` ASC, `tipo_usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_has_veiculo_usuario1`
    FOREIGN KEY (`id` , `tipo_usuario_id`)
    REFERENCES `mydb`.`usuario` (`id` , `tipo_usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_veiculo_veiculo1`
    FOREIGN KEY (`veiculo_id`)
    REFERENCES `mydb`.`veiculo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`auditoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`auditoria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` INT(1) NOT NULL,
  `usuario_id` INT NOT NULL,
  `tabela` VARCHAR(60) NOT NULL,
  `campos` TEXT NULL,
  `descricao` TEXT NULL,
  `data` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_auditoria_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_auditoria_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
